<?php

/**
 * Implements hook_menu().
 *
 * Provides a menu entry which explains what the module does.
 */
function country_menu() {
  $items = array();
  $items["country"] = array(
    'title' => 'Add content for:',
    'description' => 'Configure your country',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('country_form'),
    'access arguments' => array('access content'),
    'type' => MENU_NORMAL_ITEM,
  );
  return $items;
}

/**
 * Implements hook_form().
 *
 * declaring form
 */
function country_form($form, &$form_state) {
  global $user;
  $account = user_load($user->uid);
  $items = field_get_items('user', $account, 'field_country');
  $tax_name = array();
  if (!empty($items)) {
    foreach ($items as $item) {
      $term = taxonomy_term_load($item['tid']);
	  $country_name = isset($term->field_country_name[LANGUAGE_NONE][0]['value']) ? $term->field_country_name[LANGUAGE_NONE][0]['value'] : $term->name;
      $tax_name[$term->tid] = $country_name;
    }
  }
 
  $tid = $_SESSION['country'];
  if (!empty($tax_name)) {
  asort($tax_name);
    $form = array(
      'country' => array(
        '#type' => 'select',
        '#options' => $tax_name,
        '#default_value' => $tid,
        '#ajax' => array(
          'event' => 'change',
          'callback' => 'change_user_country',
          'progress' => array('type' => 'none'),
        ),
      ),
      'submit_button' => array(//changing button name to submit_button
        '#type' => 'submit',
        '#value' => t('Add Content'),
      ),
    );

    if(isset($form_state['values']['country'])) {
      $_SESSION['country'] = $form_state['values']['country'];
    }
  }
  else {
    $form = array(
      'message' => array(
        '#markup' => 'No country in your scope',
      ),
    );
  }
  return $form;
}

/*
 * AJAX callback for refreshing page after AJAX callback
 *
 */
function change_user_country($form, $form_state) {
  ctools_include('ajax');
  //Reload page to change the dashboard specific to selected country
  $commands[] = ctools_ajax_command_reload();
  print ajax_render($commands);
  drupal_exit();
}

/**
 * Implements hook_form_submit().
 *
 * declaring form_submit
 */
function country_form_submit($form, &$form_state) {
  global $user;
  $uid = $user->uid;
  $country = $form_state['values']['country'];
  if (!empty($country)) {
    $_SESSION['country'] = $country;
    if ($form_state['values']['op'] == 'Add Content') {
      drupal_goto("node/add");
    }
  }
  else
    drupal_goto();
}

/**
 * Implements hook_block_info().
 *
 * This hook declares what blocks are provided by the module.
 */
function country_block_info() {
  $blocks['country_selection'] = array(
    'info' => t('Switch Country'),
    'cache' => DRUPAL_NO_CACHE,
    'status' => 0,
  );
  return $blocks;
}

/**
 * Implements hook_block_view().
 *
 * This hook generates the contents of the blocks themselves.
 * 
 * This hook is generating switching country block for having drupal form in it.  
 */
function country_block_view($delta = '') {
  switch ($delta) {
    case 'country_selection':
      $block['subject'] = t('GE Country');
      $block['content'] = drupal_get_form('country_form');
      break;
  }
  return $block;
}

/**
 * Implements hook_user_login().
 */
function country_user_login(&$edit, $account) {
  $lang = field_language('user', $account, 'field_default_country');
  $user_field_list = user_load($account->uid);
  $default_country = (isset($user_field_list->field_default_country[$lang]) ? $user_field_list->field_default_country[$lang][0]['tid'] : '');
  if (!empty($default_country)) {
    $_SESSION['country'] = $default_country;
  }
}

/**
 * Implements hook user_logout(). 
 */
function country_user_logout($account) {
  unset($_SESSION['country']);
}
